version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: email_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_service
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  email-service:
    build:
      context: ../services/email-service
    container_name: email_service_api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/email_service
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - db
    ports:
      - '4000:4000'
    command: npm run dev

volumes:
  db_data:
