services:
  - type: web
    name: email-service
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://arkhives-studio.github.io/landing
    healthCheckPath: /health
    autoDeploy: true
    previews:
      enabled: false
